### ISSUE TITLE
Direct Pay 的3D驗證行為？

### ISSUE THREAD

**Issue by axacheng** [TapPay/tappay-web-example#12]
不是很確定是否台新銀行有強制要使用TapPay direct Pay的客戶啟用 3D驗證？但老闆要求所以今天還是加了three_domain_secure: true 設定到payment info，然後把這payment info丟給 TapPay.payByPrime(payment_info) 但是，怎麼嘗試都不會跳轉到台新銀行的3D驗證畫面～而是直接付款成功～請問這是否不正常？還是是因為我的信用卡卡號之前已經被記錄在tappay裡面了？(我有用 remember: true 這設定)所以不會挑轉到3D驗證畫面？

```javascript
        const payment_info = {
          prime: req.body.prime,
          merchant_id: 'xxxxxxxx'
          amount: _vcase.payPrice,
          currency: 'TWD',
          details: String(_vcase.serviceNames),
          cardholder: {
            phone_number: _vcase.userTel || '',
            name: _vcase.userName || '',
            email: _vcase.email || ''
          },
          remember: true,
          three_domain_secure: true,
          result_url: {
            backend_notify_url: 'https://34136ad3.ngrok.io/pay_result',
            frontend_redirect_url: 'https://34136ad3.ngrok.io/pay_result'
          }
        };

        tlogger.info(payment_info);

        TapPay.payByPrime(payment_info).then()
```

**Comment by axacheng** [comment]
從portal看到的是有顯示[是否開啟3D驗證 :   是] 但實際是沒有跳轉就直接付款成功了~XD
以下是production環境


![image](https://user-images.githubusercontent.com/5593412/59257189-0c28d200-8c68-11e9-976d-db73d5ad6181.png)

**Comment by Yu-Jack** [comment]
嗨嗨 ~ 您好
為了安全與隱私，就不在這邊回覆您，這邊要麻煩您直接詢問我們 LINE 的客服
可以點選此網址 [https://line.me/R/ti/p/VqXtiqzr88] 加入我們 LINE 客服
謝謝！: )

**Comment by shadow30918** [comment]
我也遇到一樣的問題，請問樓主有解了嗎?
