### ISSUE TITLE
HTTP/REST api

### ISSUE THREAD

**Issue by skyjur** [TapPay/tappay-web-example#13]
Do you have docs for your HTTP api that your TapPay-fields js sdk is built on? I would much prefer to use it directly instead of JS sdk. 

Here is example from Stripe with documentation how to add card details on their system through http api:
https://stripe.com/docs/api/payment_methods/create

**Comment by jyunliou** [comment]
The specific function which been used in TapPay-fields js sdk are not provided for directly use.
