### ISSUE TITLE
關於Backend Notify

### ISSUE THREAD

**Issue by natsumework** [TapPay/tappay-web-example#15]
您好：

目前想實做pay by prime信用卡交易後的Backend Notify，關於這部分有幾個疑問想請教  

1. 文件上是寫說3D驗證交易完成後會發送通知，這部分是只有啟用3D驗證才會做通知嗎？

2. 除了交易後的結果通知外，如果有refund或是其他交易狀態改變的話是否也會有通知？

3. 如果notify接收失敗的話tappay會不會在一段時間後重新通知呢？

4. 要如何認證收到的notify是tappay發送過來的
(有tappay的對外IP或其他資訊能讓我們驗證的嗎)

**Comment by kaojiaqi** [comment]
您好，
請使用LINE ID 或點擊以下網址，向我們客服詢問哦！
【LINE ID】@712jkrto
【網址】http://nav.cx/tqfjRQl
