### ISSUE TITLE
是不是無法支援 chrome auto fill 的功能

### ISSUE THREAD

**Issue by roadmanfong** [TapPay/tappay-web-example#16]
Hi，
我用 Direct Pay - TapPay Fields
試著加入 autocomplete credit card，
但是好像不會觸發 chrome 自動填信用卡，可能是因為每個欄位都各自包在 iframe?

https://developers.google.com/web/updates/2015/06/checkout-faster-with-autofill

**Comment by kaojiaqi** [comment]
您好，
請使用LINE ID 或點擊以下網址，向我們客服詢問哦！
【LINE ID】@712jkrto
【網址】http://nav.cx/tqfjRQl
