### ISSUE TITLE
有點不太懂

### ISSUE THREAD

**Issue by mypetertw** [TapPay/tappay-web-example#2]
範例中：然後再用 TapPay.redirect(payment_url) 到 Line Pay 付款頁面

這句我不太懂噎？哪裡才是Line Pay 付款頁面呢
有順利取到Prime了（按下按鈕就有）
但怎麼連接 ＬＩＮＥＰＡＹ啊？

**Comment by Yu-Jack** [comment]
HI @mypetertw 
這邊你取得 Prime 之後
你要用下面有一個 curl 的指令並把 prime 的值帶進去做 pay by prime
Pay by Prime 之後才會回傳付款頁面
