### ISSUE TITLE
tappay fields ccv 輸入 `12a` 也會暫時視為通過

### ISSUE THREAD

**Issue by roadmanfong** [TapPay/tappay-web-example#23]
https://user-images.githubusercontent.com/2047789/128470831-fdf1960e-f3b6-49af-a35e-98603477ef82.mp4

雖然 blur 後會再檢查為失效，
有辦法把 `12a` 這種狀況視為無效嗎？

**Comment by jyunliou** [comment]
未來我們會將這點排入優化，謝謝。

**Comment by jyunliou** [comment]
已於 v5.13.0 修正此問題。
