### ISSUE TITLE
到期日欄位狀態有時未能正確更新

### ISSUE THREAD

**Issue by zbryikt** [TapPay/tappay-web-example#26]
使用 Direct Pay - iframe 時, 到期日部份如果用貼上的, 即便填完仍會回報欄位未完成

可以在此示範頁面重現, 所以應該跟套件用戶端程式碼無關
 - https://tappay.github.io/tappay-web-example/Direct_Pay_iframe/example/index.html

測試環境: 
 - Google Chrome 105.0.5195.127, Windows 7
 - Google Chrome 105.0.5195.125, macOS 12.2.1

測試步驟 
 - 在到期日欄位先輸入 1234, 確認程式回報已填好沒問題
 - 在到期日框中依序按 ctrl-a ctrl-x ctrl-v 全選剪下後直接再貼上
 - 這時資料已重新填妥, 但程式會顯示使用者尚在輸入中

用戶回報才注意到的現象, 但對方僅回報完成的欄位未被驗證(因此造成無法付款), 實際輸入手段不明, 上述的重現手段僅是我測試時發現的, 不確定是否有其它的因素造成狀態未正確更新.

用戶端程式這邊在貼上動作執行時不會收到 update 事件 (onUpdate 未被觸發), polling TPDirect.card.getTappayFieldsStatus() 得到的數值也都是 3.

**Comment by kaojiaqi** [comment]
@zbryikt 
後續會排入修復
謝謝

**Comment by kaojiaqi** [comment]
@zbryikt 目前已經修復，可以將 sdk 更新到 v5.19.1
