### ISSUE TITLE
前端有npm 打包嗎？

### ISSUE THREAD

**Issue by wildfrontend** [TapPay/tappay-web-example#3]
目前用react 寫程式

想說SDk打包成NPM 比較好操作

**Comment by Yu-Jack** [comment]
@Louis-Chen 
不好意思，目前還尚未提供 npm 讓客戶去操作
但未來我們會把這點考量進去做設計

**Comment by yusef-ho** [comment]
這issue都兩年了....何時要處理啊！

**Comment by yenchenLiu** [comment]
我們公司也需要
