### ISSUE TITLE
請問如何串接產生付款連結？

### ISSUE THREAD

**Issue by gkfat** [TapPay/tappay-web-example#32]
您好，Tappay portal 有一項功能是「連結付款」，因為公司有在服務端產生付款連結，再發送給消費者進行付款的需求，但在開發者文件中找不到相關 API，請問有辦法可以串接此功能嗎？

**Comment by kaojiaqi** [comment]
@gkfat 
連結付款有 API 可以串接
請聯絡我們的服務團隊

LINE 帳號：@tappay_official
信箱：support@cherri.tech
