### ISSUE TITLE
Auto Focus on Field 失效

### ISSUE THREAD

**Issue by zalic0814** [TapPay/tappay-web-example#33]
Hi
請問，要如何做到類似[這範例](https://github.com/TapPay/tappay-web-example/tree/master/TapPay_Fields)的 gif 效果：當填完卡號後，自動 focus 卡片到期日。

這 [DEMO](https://tappay.github.io/tappay-web-example/TapPay_Fields/example/index.html) 在 edge, safari, mobile web view 都失去了這功能。

查了一些文件也沒看到相關說明，期待您的回覆。

**Comment by kaojiaqi** [comment]
@zalic0814 
你好
自動 focus 卡片到期日
這個功能是不用另外設定
當卡號符合信用卡格式
就會自動 focus 到到期日

目前 Safari 的底層運作機制關係，無法支援
Edge 是可以正常自動 focus 的
mobile web 不確定您是使用 iOS 系統還是 android 系統及實作方式

或是可以在聯絡 TapPay 的官方 @tappay_official
謝謝

**Comment by zalic0814** [comment]
@kaojiaqi 
感謝回覆

> mobile web 不確定您是使用 iOS 系統還是 android 系統及實作方式

我們用 Angular + ionic 跑在 Ios 上
