### ISSUE TITLE
請問有生成LinkPay付款連結的API嗎？

### ISSUE THREAD

**Issue by axacheng** [TapPay/tappay-web-example#8]
目前只能從TapPay portal去生成 [付款連結] ，希望能夠整合我們的程式把付款內容透過LinkPay API (如果有的話) 去自動生成，這樣就不需要登入到TapPay portal裡面人為操作。

因為沒有在文件上看到有LinkPay API, 所以想在這邊發問和你們確認一下。

感謝

**Comment by Yu-Jack** [comment]
@axacheng  您好 ~

非常抱歉我們目前沒有提供 Link Pay API 使用 😢

**Comment by axacheng** [comment]
好的沒問題 👍 。
我們也可以自己做 [付款連結]


感謝
